### ISSUE TITLE
require fails in nodejs ReferenceError: window is not defined

### ISSUE THREAD

**Issue by brakdag** [Hagsten/Talkify#27]
```javascript
 var talkify = require('talkify-tts')
ReferenceError: window is not defined
    at Object.1../src/promise.js (D:\temp\tts\node_modules\talkify-tts\dist\talkify.js:2:1)
    at s (D:\temp\tts\node_modules\talkify-tts\dist\talkify.js:1:316)
    at e (D:\temp\tts\node_modules\talkify-tts\dist\talkify.js:1:487)
```

**Comment by Hagsten** [comment]
It seems wierd that we requrie "window" for Promise...but, generally, this library is built with a browser in mind, there is therefore no official support for node. There are several areas in the source code that explicily requires the window object:

- WebSpeech API (window.speechSynthesis)
- window.setTimeout/clearTimeout for speech marks

There are also serveral areas where there are direct DOM-manipulation.
